using Rec_Partapgarh.Models; using System; using System.Collections.Generic; using System.Configuration; using System.Data.SqlClient; using System.IO; using System.Web.Mvc;
namespace Rec_Partapgarh.Controllers.API
{
 public class AcademicCalendarApiController:Controller{const string Admin="superAdmin";readonly string cs=ConfigurationManager.ConnectionStrings["recpLocalDb"].ConnectionString;
 [HttpGet]public JsonResult List(){var d=new List<object>();using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT AcademicCalendarId,Title,SemesterType,FilePath,IsActive,CreatedBy,UpdatedBy FROM dbo.tbl_AcademicCalendar ORDER BY AcademicCalendarId DESC",c)){c.Open();using(var r=q.ExecuteReader())while(r.Read()){var p=r.GetString(3);d.Add(new{AcademicCalendarId=r.GetInt32(0),Title=r.GetString(1),SemesterType=r.GetString(2),FilePath=p,FileUrl=Url.Content(p),IsActive=r.GetBoolean(4),CreatedBy=r.GetString(5),UpdatedBy=r.IsDBNull(6)?null:r.GetString(6)});}}return Json(new{success=true,data=d},JsonRequestBehavior.AllowGet);}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult Save(ManagerAcademicCalendar m){m.Title=(m.Title??"").Trim();m.SemesterType=(m.SemesterType??"").Trim();var f=Request.Files["CalendarFile"];var e=new Dictionary<string,string>();if(string.IsNullOrWhiteSpace(m.Title))e["CalendarTitle"]="Title is required.";else if(m.Title.Length>200)e["CalendarTitle"]="Maximum 200 characters allowed.";if(m.SemesterType!="Odd Semester"&&m.SemesterType!="Even Semester")e["CalendarSemester"]="Select a valid semester.";if(m.AcademicCalendarId==0&&(f==null||f.ContentLength==0))e["CalendarFile"]="PDF or DOCX file is required.";if(f!=null&&f.ContentLength>0){var x=Path.GetExtension(f.FileName).ToLowerInvariant();var t=(f.ContentType??"").ToLowerInvariant();var valid=(x==".pdf"&&t=="application/pdf")||(x==".docx"&&t=="application/vnd.openxmlformats-officedocument.wordprocessingml.document");if(!valid)e["CalendarFile"]="Only valid PDF or DOCX files are allowed.";else if(f.ContentLength>3*1024*1024)e["CalendarFile"]="File size cannot exceed 3 MB.";}if(e.Count>0)return Json(new{success=false,message="Please correct the validation errors.",errors=e});var old=m.AcademicCalendarId>0?GetFile(m.AcademicCalendarId):null;if(m.AcademicCalendarId>0&&old==null)return Json(new{success=false,message="Academic calendar not found."});string added=null;try{if(f!=null&&f.ContentLength>0){var dir=Server.MapPath("~/Content/uploads/manager/calendar");Directory.CreateDirectory(dir);var n=Guid.NewGuid().ToString("N")+Path.GetExtension(f.FileName).ToLowerInvariant();f.SaveAs(Path.Combine(dir,n));added="~/Content/uploads/manager/calendar/"+n;}using(var c=new SqlConnection(cs))using(var q=c.CreateCommand()){q.CommandText=m.AcademicCalendarId==0?"INSERT dbo.tbl_AcademicCalendar(Title,SemesterType,FilePath,IsActive,CreatedBy) VALUES(@t,@sm,@f,@s,@by)":"UPDATE dbo.tbl_AcademicCalendar SET Title=@t,SemesterType=@sm,FilePath=@f,IsActive=@s,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE AcademicCalendarId=@id";q.Parameters.AddWithValue("@t",m.Title);q.Parameters.AddWithValue("@sm",m.SemesterType);q.Parameters.AddWithValue("@f",added??old);q.Parameters.AddWithValue("@s",m.IsActive);q.Parameters.AddWithValue("@by",Admin);if(m.AcademicCalendarId>0)q.Parameters.AddWithValue("@id",m.AcademicCalendarId);c.Open();q.ExecuteNonQuery();}if(added!=null&&old!=null)DeleteFile(old);return Json(new{success=true,message=m.AcademicCalendarId==0?"Academic calendar added successfully.":"Academic calendar updated successfully."});}catch{if(added!=null)DeleteFile(added);return Json(new{success=false,message="Unable to save academic calendar."});}}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult ToggleStatus(int id){return Run("UPDATE dbo.tbl_AcademicCalendar SET IsActive=CASE WHEN IsActive=1 THEN 0 ELSE 1 END,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE AcademicCalendarId=@id",id,"Academic calendar status updated.");}[HttpPost,ValidateAntiForgeryToken]public JsonResult Delete(int id){var p=GetFile(id);if(p==null)return Json(new{success=false,message="Academic calendar not found."});var r=Run("DELETE dbo.tbl_AcademicCalendar WHERE AcademicCalendarId=@id",id,"Academic calendar deleted successfully.");DeleteFile(p);return r;}
 string GetFile(int id){using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT FilePath FROM dbo.tbl_AcademicCalendar WHERE AcademicCalendarId=@id",c)){q.Parameters.AddWithValue("@id",id);c.Open();return q.ExecuteScalar()as string;}}void DeleteFile(string p){if(string.IsNullOrEmpty(p)||!p.StartsWith("~/Content/uploads/manager/calendar/",StringComparison.OrdinalIgnoreCase))return;var x=Server.MapPath(p);if(System.IO.File.Exists(x))System.IO.File.Delete(x);}JsonResult Run(string s,int id,string m){using(var c=new SqlConnection(cs))using(var q=new SqlCommand(s,c)){q.Parameters.AddWithValue("@id",id);if(s.Contains("@by"))q.Parameters.AddWithValue("@by",Admin);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Academic calendar not found."});}return Json(new{success=true,message=m});}
 }
}
