using Rec_Partapgarh.Models;
using System; using System.Collections.Generic; using System.Configuration; using System.Data; using System.Data.SqlClient; using System.IO; using System.Linq; using System.Web; using System.Web.Mvc;
namespace Rec_Partapgarh.Controllers.API
{
    public class GeneralNoticeApiController : Controller
    {
        const string Admin="superAdmin"; readonly string cs=ConfigurationManager.ConnectionStrings["recpLocalDb"].ConnectionString;
        [HttpGet] public JsonResult List(){var data=new List<object>();using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT NoticeId,NoticeType,Title,FilePath,IsActive,CreatedBy,UpdatedBy FROM dbo.tbl_GeneralNotice ORDER BY NoticeId DESC",c)){c.Open();using(var r=q.ExecuteReader())while(r.Read()){var p=r.GetString(3);data.Add(new{NoticeId=r.GetInt32(0),NoticeType=r.GetString(1),Title=r.GetString(2),FilePath=p,FileUrl=Url.Content(p),IsActive=r.GetBoolean(4),CreatedBy=r.GetString(5),UpdatedBy=r.IsDBNull(6)?null:r.GetString(6)});}}return Json(new{success=true,data},JsonRequestBehavior.AllowGet);}
        [HttpPost,ValidateAntiForgeryToken] public JsonResult Save(ManagerGeneralNotice m){m.Title=(m.Title??"").Trim();m.NoticeType=(m.NoticeType??"").Trim();var f=Request.Files["NoticeFile"];var e=new Dictionary<string,string>();if(m.NoticeType!="Horizontal"&&m.NoticeType!="Vertical")e["NoticeType"]="Select a valid notice type.";if(string.IsNullOrWhiteSpace(m.Title))e["NoticeTitle"]="Title is required.";else if(m.Title.Length>200)e["NoticeTitle"]="Title cannot exceed 200 characters.";if(m.NoticeId==0&&(f==null||f.ContentLength==0))e["NoticeFile"]="PDF or DOCX file is required.";if(f!=null&&f.ContentLength>0){var x=Path.GetExtension(f.FileName).ToLowerInvariant();var ct=(f.ContentType??"").ToLowerInvariant();var valid=(x==".pdf"&&ct=="application/pdf")||(x==".docx"&&ct=="application/vnd.openxmlformats-officedocument.wordprocessingml.document");if(!valid)e["NoticeFile"]="Only valid PDF or DOCX files are allowed.";else if(f.ContentLength>3*1024*1024)e["NoticeFile"]="File size cannot exceed 3 MB.";}if(e.Count>0)return Json(new{success=false,message="Please correct the validation errors.",errors=e});string old=m.NoticeId>0?PathFor(m.NoticeId):null;if(m.NoticeId>0&&old==null)return Json(new{success=false,message="Notice not found."});string added=null;try{if(f!=null&&f.ContentLength>0){var dir=Server.MapPath("~/Content/uploads/manager/notices");Directory.CreateDirectory(dir);var n=Guid.NewGuid().ToString("N")+Path.GetExtension(f.FileName).ToLowerInvariant();f.SaveAs(Path.Combine(dir,n));added="~/Content/uploads/manager/notices/"+n;}using(var c=new SqlConnection(cs))using(var q=c.CreateCommand()){q.CommandText=m.NoticeId==0?"INSERT dbo.tbl_GeneralNotice(NoticeType,Title,FilePath,IsActive,CreatedBy) VALUES(@t,@n,@f,@s,@by)":"UPDATE dbo.tbl_GeneralNotice SET NoticeType=@t,Title=@n,FilePath=@f,IsActive=@s,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE NoticeId=@id";q.Parameters.AddWithValue("@t",m.NoticeType);q.Parameters.AddWithValue("@n",m.Title);q.Parameters.AddWithValue("@f",added??old);q.Parameters.AddWithValue("@s",m.IsActive);q.Parameters.AddWithValue("@by",Admin);if(m.NoticeId>0)q.Parameters.AddWithValue("@id",m.NoticeId);c.Open();q.ExecuteNonQuery();}if(added!=null&&old!=null)DeleteFile(old);return Json(new{success=true,message=m.NoticeId==0?"Notice added successfully.":"Notice updated successfully."});}catch{if(added!=null)DeleteFile(added);return Json(new{success=false,message="Unable to save notice."});}}
        [HttpPost,ValidateAntiForgeryToken] public JsonResult ToggleStatus(int id){return Change("UPDATE dbo.tbl_GeneralNotice SET IsActive=CASE WHEN IsActive=1 THEN 0 ELSE 1 END,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE NoticeId=@id",id,"Notice status updated.");}
        [HttpPost,ValidateAntiForgeryToken] public JsonResult Delete(int id){var p=PathFor(id);if(p==null)return Json(new{success=false,message="Notice not found."});var x=Change("DELETE dbo.tbl_GeneralNotice WHERE NoticeId=@id",id,"Notice deleted successfully.");DeleteFile(p);return x;}
        JsonResult Change(string sql,int id,string msg){using(var c=new SqlConnection(cs))using(var q=new SqlCommand(sql,c)){q.Parameters.AddWithValue("@id",id);if(sql.Contains("@by"))q.Parameters.AddWithValue("@by",Admin);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Notice not found."});}return Json(new{success=true,message=msg});}
        string PathFor(int id){using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT FilePath FROM dbo.tbl_GeneralNotice WHERE NoticeId=@id",c)){q.Parameters.AddWithValue("@id",id);c.Open();return q.ExecuteScalar() as string;}}
        void DeleteFile(string p){if(string.IsNullOrEmpty(p)||!p.StartsWith("~/Content/uploads/manager/notices/",StringComparison.OrdinalIgnoreCase))return;var x=Server.MapPath(p);if(System.IO.File.Exists(x))System.IO.File.Delete(x);}
    }
}
