using Rec_Partapgarh.Models; using System; using System.Collections.Generic; using System.Configuration; using System.Data.SqlClient; using System.IO; using System.Linq; using System.Web.Mvc;
namespace Rec_Partapgarh.Controllers.API
{
 public class ManagerGalleryApiController:Controller{const string Admin="superAdmin";readonly string cs=ConfigurationManager.ConnectionStrings["recpLocalDb"].ConnectionString;static readonly string[] Ext={".jpg",".jpeg",".png",".webp"};static readonly string[] Types={"image/jpeg","image/png","image/webp"};
 [HttpGet]public JsonResult List(){var d=new List<object>();using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT g.GalleryId,g.CategoryId,c.CategoryName,g.Title,g.ImagePath,g.IsActive,g.CreatedBy,g.UpdatedBy FROM dbo.tbl_Gallery g JOIN dbo.tbl_gallery_category c ON c.CategoryId=g.CategoryId ORDER BY g.GalleryId DESC",c)){c.Open();using(var r=q.ExecuteReader())while(r.Read()){var p=r.GetString(4);d.Add(new{GalleryId=r.GetInt32(0),CategoryId=r.GetInt32(1),CategoryName=r.GetString(2),Title=r.IsDBNull(3)?null:r.GetString(3),ImagePath=p,ImageUrl=Url.Content(p),IsActive=r.GetBoolean(5),CreatedBy=r.GetString(6),UpdatedBy=r.IsDBNull(7)?null:r.GetString(7)});}}return Json(new{success=true,data=d},JsonRequestBehavior.AllowGet);}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult Save(ManagerGallery m){m.Title=(m.Title??"").Trim();var f=Request.Files["GalleryImage"];var e=new Dictionary<string,string>();if(!ValidCategory(m.CategoryId))e["GalleryCategory"]="Select a valid category.";if(m.Title.Length>200)e["GalleryTitle"]="Maximum 200 characters allowed.";if(m.GalleryId==0&&(f==null||f.ContentLength==0))e["GalleryImage"]="Gallery image is required.";if(f!=null&&f.ContentLength>0){var x=Path.GetExtension(f.FileName).ToLowerInvariant();var t=(f.ContentType??"").ToLowerInvariant();if(!Ext.Contains(x)||!Types.Contains(t))e["GalleryImage"]="Only JPG, PNG or WEBP images are allowed.";else if(f.ContentLength>3*1024*1024)e["GalleryImage"]="Image size cannot exceed 3 MB.";}if(e.Count>0)return Json(new{success=false,message="Please correct the validation errors.",errors=e});var old=m.GalleryId>0?GetImage(m.GalleryId):null;if(m.GalleryId>0&&old==null)return Json(new{success=false,message="Gallery record not found."});string added=null;try{if(f!=null&&f.ContentLength>0){var dir=Server.MapPath("~/Content/uploads/manager/gallery");Directory.CreateDirectory(dir);var n=Guid.NewGuid().ToString("N")+Path.GetExtension(f.FileName).ToLowerInvariant();f.SaveAs(Path.Combine(dir,n));added="~/Content/uploads/manager/gallery/"+n;}using(var c=new SqlConnection(cs))using(var q=c.CreateCommand()){q.CommandText=m.GalleryId==0?"INSERT dbo.tbl_Gallery(CategoryId,Title,ImagePath,IsActive,CreatedBy) VALUES(@c,@t,@i,@s,@by)":"UPDATE dbo.tbl_Gallery SET CategoryId=@c,Title=@t,ImagePath=@i,IsActive=@s,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE GalleryId=@id";q.Parameters.AddWithValue("@c",m.CategoryId);q.Parameters.AddWithValue("@t",string.IsNullOrEmpty(m.Title)?(object)DBNull.Value:m.Title);q.Parameters.AddWithValue("@i",added??old);q.Parameters.AddWithValue("@s",m.IsActive);q.Parameters.AddWithValue("@by",Admin);if(m.GalleryId>0)q.Parameters.AddWithValue("@id",m.GalleryId);c.Open();q.ExecuteNonQuery();}if(added!=null&&old!=null)DeleteImage(old);return Json(new{success=true,message=m.GalleryId==0?"Gallery image added successfully.":"Gallery updated successfully."});}catch{if(added!=null)DeleteImage(added);return Json(new{success=false,message="Unable to save gallery."});}}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult ToggleStatus(int id){return Run("UPDATE dbo.tbl_Gallery SET IsActive=CASE WHEN IsActive=1 THEN 0 ELSE 1 END,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE GalleryId=@id",id,"Gallery status updated.");}[HttpPost,ValidateAntiForgeryToken]public JsonResult Delete(int id){var p=GetImage(id);if(p==null)return Json(new{success=false,message="Gallery record not found."});var r=Run("DELETE dbo.tbl_Gallery WHERE GalleryId=@id",id,"Gallery deleted successfully.");DeleteImage(p);return r;}
 bool ValidCategory(int id){using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT COUNT(1) FROM dbo.tbl_gallery_category WHERE CategoryId=@id AND IsActive=1",c)){q.Parameters.AddWithValue("@id",id);c.Open();return(int)q.ExecuteScalar()>0;}}string GetImage(int id){using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT ImagePath FROM dbo.tbl_Gallery WHERE GalleryId=@id",c)){q.Parameters.AddWithValue("@id",id);c.Open();return q.ExecuteScalar()as string;}}void DeleteImage(string p){if(string.IsNullOrEmpty(p)||!p.StartsWith("~/Content/uploads/manager/gallery/",StringComparison.OrdinalIgnoreCase))return;var x=Server.MapPath(p);if(System.IO.File.Exists(x))System.IO.File.Delete(x);}JsonResult Run(string s,int id,string m){using(var c=new SqlConnection(cs))using(var q=new SqlCommand(s,c)){q.Parameters.AddWithValue("@id",id);if(s.Contains("@by"))q.Parameters.AddWithValue("@by",Admin);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Gallery record not found."});}return Json(new{success=true,message=m});}
 }
}
