using Rec_Partapgarh.Models; using System; using System.Collections.Generic; using System.Configuration; using System.Data.SqlClient; using System.IO; using System.Linq; using System.Web.Mvc;
namespace Rec_Partapgarh.Controllers.API
{
 public class PressReleaseApiController:Controller{const string Admin="superAdmin";readonly string cs=ConfigurationManager.ConnectionStrings["recpLocalDb"].ConnectionString;static readonly string[] Ext={".jpg",".jpeg",".png",".webp"};static readonly string[] Types={"image/jpeg","image/png","image/webp"};
 [HttpGet]public JsonResult List(){var d=new List<object>();using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT PressReleaseId,Title,ImagePath,IsActive,CreatedBy,UpdatedBy FROM dbo.tbl_PressRelease ORDER BY PressReleaseId DESC",c)){c.Open();using(var r=q.ExecuteReader())while(r.Read()){var p=r.GetString(2);d.Add(new{PressReleaseId=r.GetInt32(0),Title=r.GetString(1),ImagePath=p,ImageUrl=Url.Content(p),IsActive=r.GetBoolean(3),CreatedBy=r.GetString(4),UpdatedBy=r.IsDBNull(5)?null:r.GetString(5)});}}return Json(new{success=true,data=d},JsonRequestBehavior.AllowGet);}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult Save(ManagerPressRelease m){m.Title=(m.Title??"").Trim();var f=Request.Files["PressImage"];var e=new Dictionary<string,string>();if(string.IsNullOrWhiteSpace(m.Title))e["PressTitle"]="Title is required.";else if(m.Title.Length>200)e["PressTitle"]="Maximum 200 characters allowed.";if(m.PressReleaseId==0&&(f==null||f.ContentLength==0))e["PressImage"]="Press release image is required.";if(f!=null&&f.ContentLength>0){var x=Path.GetExtension(f.FileName).ToLowerInvariant();var t=(f.ContentType??"").ToLowerInvariant();if(!Ext.Contains(x)||!Types.Contains(t))e["PressImage"]="Only JPG, PNG or WEBP images are allowed.";else if(f.ContentLength>3*1024*1024)e["PressImage"]="Image size cannot exceed 3 MB.";}if(e.Count>0)return Json(new{success=false,message="Please correct the validation errors.",errors=e});var old=m.PressReleaseId>0?GetImage(m.PressReleaseId):null;if(m.PressReleaseId>0&&old==null)return Json(new{success=false,message="Press release not found."});string added=null;try{if(f!=null&&f.ContentLength>0){var dir=Server.MapPath("~/Content/uploads/manager/press");Directory.CreateDirectory(dir);var n=Guid.NewGuid().ToString("N")+Path.GetExtension(f.FileName).ToLowerInvariant();f.SaveAs(Path.Combine(dir,n));added="~/Content/uploads/manager/press/"+n;}using(var c=new SqlConnection(cs))using(var q=c.CreateCommand()){q.CommandText=m.PressReleaseId==0?"INSERT dbo.tbl_PressRelease(Title,ImagePath,IsActive,CreatedBy) VALUES(@t,@i,@s,@by)":"UPDATE dbo.tbl_PressRelease SET Title=@t,ImagePath=@i,IsActive=@s,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE PressReleaseId=@id";q.Parameters.AddWithValue("@t",m.Title);q.Parameters.AddWithValue("@i",added??old);q.Parameters.AddWithValue("@s",m.IsActive);q.Parameters.AddWithValue("@by",Admin);if(m.PressReleaseId>0)q.Parameters.AddWithValue("@id",m.PressReleaseId);c.Open();q.ExecuteNonQuery();}if(added!=null&&old!=null)DeleteImage(old);return Json(new{success=true,message=m.PressReleaseId==0?"Press release added successfully.":"Press release updated successfully."});}catch{if(added!=null)DeleteImage(added);return Json(new{success=false,message="Unable to save press release."});}}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult ToggleStatus(int id){return Run("UPDATE dbo.tbl_PressRelease SET IsActive=CASE WHEN IsActive=1 THEN 0 ELSE 1 END,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE PressReleaseId=@id",id,"Press release status updated.");}[HttpPost,ValidateAntiForgeryToken]public JsonResult Delete(int id){var p=GetImage(id);if(p==null)return Json(new{success=false,message="Press release not found."});var r=Run("DELETE dbo.tbl_PressRelease WHERE PressReleaseId=@id",id,"Press release deleted successfully.");DeleteImage(p);return r;}
 string GetImage(int id){using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT ImagePath FROM dbo.tbl_PressRelease WHERE PressReleaseId=@id",c)){q.Parameters.AddWithValue("@id",id);c.Open();return q.ExecuteScalar()as string;}}void DeleteImage(string p){if(string.IsNullOrEmpty(p)||!p.StartsWith("~/Content/uploads/manager/press/",StringComparison.OrdinalIgnoreCase))return;var x=Server.MapPath(p);if(System.IO.File.Exists(x))System.IO.File.Delete(x);}JsonResult Run(string s,int id,string m){using(var c=new SqlConnection(cs))using(var q=new SqlCommand(s,c)){q.Parameters.AddWithValue("@id",id);if(s.Contains("@by"))q.Parameters.AddWithValue("@by",Admin);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Press release not found."});}return Json(new{success=true,message=m});}
 }
}
