using System; using System.Collections.Generic; using System.Configuration; using System.Data.SqlClient; using System.Web.Mvc;
namespace Rec_Partapgarh.Controllers.API
{
 public class VideoApiController:Controller{const string Admin="superAdmin";readonly string cs=ConfigurationManager.ConnectionStrings["recpLocalDb"].ConnectionString;
 [HttpGet]public JsonResult List(){var d=new List<object>();using(var c=new SqlConnection(cs))using(var q=new SqlCommand("SELECT VideoId,Title,SourceUrl,IsActive,CreatedBy,UpdatedBy FROM dbo.tbl_Video ORDER BY VideoId DESC",c)){c.Open();using(var r=q.ExecuteReader())while(r.Read())d.Add(new{VideoId=r.GetInt32(0),Title=r.GetString(1),SourceUrl=r.GetString(2),IsActive=r.GetBoolean(3),CreatedBy=r.GetString(4),UpdatedBy=r.IsDBNull(5)?null:r.GetString(5)});}return Json(new{success=true,data=d},JsonRequestBehavior.AllowGet);}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult Save(int VideoId,string Title,string SourceUrl,bool IsActive){Title=(Title??"").Trim();SourceUrl=(SourceUrl??"").Trim();var e=new Dictionary<string,string>();if(string.IsNullOrWhiteSpace(Title))e["VideoTitle"]="Title is required.";else if(Title.Length>200)e["VideoTitle"]="Maximum 200 characters allowed.";Uri u;if(!Uri.TryCreate(SourceUrl,UriKind.Absolute,out u)||u.Scheme!="https"||!ValidSource(u))e["SourceUrl"]="Enter a valid YouTube embed or Google Drive URL.";else if(SourceUrl.Length>500)e["SourceUrl"]="URL cannot exceed 500 characters.";if(e.Count>0)return Json(new{success=false,message="Please correct the validation errors.",errors=e});using(var c=new SqlConnection(cs))using(var q=c.CreateCommand()){q.CommandText=VideoId==0?"INSERT dbo.tbl_Video(Title,SourceUrl,IsActive,CreatedBy) VALUES(@t,@u,@s,@by)":"UPDATE dbo.tbl_Video SET Title=@t,SourceUrl=@u,IsActive=@s,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE VideoId=@id";q.Parameters.AddWithValue("@t",Title);q.Parameters.AddWithValue("@u",SourceUrl);q.Parameters.AddWithValue("@s",IsActive);q.Parameters.AddWithValue("@by",Admin);if(VideoId>0)q.Parameters.AddWithValue("@id",VideoId);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Video not found."});}return Json(new{success=true,message=VideoId==0?"Video added successfully.":"Video updated successfully."});}
 bool ValidSource(Uri u){var h=u.Host.ToLowerInvariant();return ((h=="www.youtube.com"||h=="youtube.com"||h=="www.youtube-nocookie.com")&&u.AbsolutePath.StartsWith("/embed/"))||h=="drive.google.com";}
 [HttpPost,ValidateAntiForgeryToken]public JsonResult ToggleStatus(int id){return Run("UPDATE dbo.tbl_Video SET IsActive=CASE WHEN IsActive=1 THEN 0 ELSE 1 END,UpdatedAt=SYSDATETIME(),UpdatedBy=@by WHERE VideoId=@id",id,"Video status updated.");}[HttpPost,ValidateAntiForgeryToken]public JsonResult Delete(int id){return Run("DELETE dbo.tbl_Video WHERE VideoId=@id",id,"Video deleted successfully.");}JsonResult Run(string s,int id,string m){using(var c=new SqlConnection(cs))using(var q=new SqlCommand(s,c)){q.Parameters.AddWithValue("@id",id);if(s.Contains("@by"))q.Parameters.AddWithValue("@by",Admin);c.Open();if(q.ExecuteNonQuery()==0)return Json(new{success=false,message="Video not found."});}return Json(new{success=true,message=m});}}
}
