//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rec_Partapgarh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_tenders
    {
        public int Id { get; set; }
        public string notification { get; set; }
        public string file { get; set; }
        public string urllink { get; set; }
        public System.DateTime doa { get; set; }
    }
}
