//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rec_Partapgarh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grievance
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string RollNumber { get; set; }
        public string CourseBranch { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Place { get; set; }
        public string IncidentDetails { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
    }
}
