//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rec_Partapgarh.Models
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    
    public partial class recpEntities : DbContext
    {
        public recpEntities()
            : base(BuildEntityConnectionString())
        {
        }

        private static string BuildEntityConnectionString()
        {
            var localConnection = ConfigurationManager.ConnectionStrings["recpLocalDb"];
            if (localConnection == null || string.IsNullOrWhiteSpace(localConnection.ConnectionString))
            {
                throw new InvalidOperationException("The recpLocalDb connection string is missing.");
            }

            var builder = new EntityConnectionStringBuilder
            {
                Metadata = "res://*/Models.recmodel.csdl|res://*/Models.recmodel.ssdl|res://*/Models.recmodel.msl",
                Provider = "System.Data.SqlClient",
                ProviderConnectionString = localConnection.ConnectionString
            };

            return builder.ConnectionString;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GalleryImage> GalleryImages { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Academic_Committee> Academic_Committee { get; set; }
        public virtual DbSet<AcademicCalendar> AcademicCalendars { get; set; }
        public virtual DbSet<AICTE> AICTEs { get; set; }
        public virtual DbSet<Circular> Circulars { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<etender> etenders { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<G_O_for_Change> G_O_for_Change { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Grievance> Grievances { get; set; }
        public virtual DbSet<IQAC> IQACs { get; set; }
        public virtual DbSet<List_of_Holidays> List_of_Holidays { get; set; }
        public virtual DbSet<Memorandum_of_Association> Memorandum_of_Association { get; set; }
        public virtual DbSet<Minutes_of_Meeting> Minutes_of_Meeting { get; set; }
        public virtual DbSet<Mou> Mous { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<notificationfile> notificationfiles { get; set; }
        public virtual DbSet<RecentActivity> RecentActivities { get; set; }
        public virtual DbSet<Silder> Silders { get; set; }
        public virtual DbSet<Society_Bylaws> Society_Bylaws { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<e_tenders> e_tenders { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<MediaCoverage> MediaCoverages { get; set; }
        public virtual DbSet<PressReleas> PressReleases { get; set; }
    }
}
