//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rec_Partapgarh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Silder
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Heading { get; set; }
        public string Paragraph { get; set; }
        public Nullable<System.DateTime> Dos { get; set; }
        public string Status { get; set; }
    }
}
